### ISSUE TITLE
SassError with docusaurus v2.4.0

### ISSUE THREAD

**Issue by Zenahr** [PaloAltoNetworks/docusaurus-openapi-docs#568]
## Steps to reproduce

1. `yarn add docusaurus-plugin-openapi-docs@2.0.0-beta.2`
2. `yarn add docusaurus-theme-openapi-docs@2.0.0-beta.2`
3. Edit docusaurus.config.js based on [the readme](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs#configuring-docusaurusconfigjs-plugin-and-theme-usage)
4. `yarn dev` to run the local preview server

## Expected behavior

Don't throw an error.

## Current behavior

Throws an error. Stacktrace:

```

SassError: expected "{".
  ╷
5 │       var cssReload = require("../../../mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js")(module.id, {"esModule":true,"locals":false});
  │

             ^
  ╵
  node_modules\docusaurus-theme-openapi-docs\lib\theme\styles.scss 5:142  root stylesheet
SassError: expected "{".
  ╷
5 │       var cssReload = require("../../../node_modules/mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js")(module.id, {"esModule":true,"locals":false});
  │

                          ^
  ╵
  src\css\custom\main.scss 5:155  root stylesheet
SassError: expected "{".
  ╷
5 │       var cssReload = require("../../../mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js")(module.id, {"esModule":true,"locals":false});
  │

             ^
  ╵
  node_modules\docusaurus-theme-openapi-docs\lib\theme\styles.scss 5:142  root stylesheet
-- inner error --
SassError: expected "{".
  ╷
5 │       var cssReload = require("../../../mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js")(module.id, {"esModule":true,"locals":false});
  │

             ^
  ╵
  node_modules\docusaurus-theme-openapi-docs\lib\theme\styles.scss 5:142  root stylesheet
Generated code for C:\PRODUCT-DOCS\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[13].oneOf[1].use[1]!C:\PRODUCT-DOCS\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[13].oneOf[1].use[2]!C:\PRODUCT-DOCS\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[13].oneOf[1].use[3]!C:\PRODUCT-DOCS\node_modules\mini-css-extract-plugin\dist\loader.js??ruleSet[1].rules[16].oneOf[1].use[0]!C:\PRODUCT-DOCS\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[16].oneOf[1].use[1]!C:\PRODUCT-DOCS\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[16].oneOf[1].use[2]!C:\PRODUCT-DOCS\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[16].oneOf[1].use[3]!C:\PRODUCT-DOCS\node_modules\docusaurus-theme-openapi-docs\lib\theme\styles.scss
SassError: expected "{".
  ╷
5 │       var cssReload = require("../../../node_modules/mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js")(module.id, {"esModule":true,"locals":false});
  │

                          ^
  ╵
  src\css\custom\main.scss 5:155  root stylesheet
-- inner error --
SassError: expected "{".
  ╷
5 │       var cssReload = require("../../../node_modules/mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js")(module.id, {"esModule":true,"locals":false});
  │

                          ^
  ╵
  src\css\custom\main.scss 5:155  root stylesheet
Generated code for C:\PRODUCT-DOCS\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[13].oneOf[1].use[1]!C:\PRODUCT-DOCS\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[13].oneOf[1].use[2]!C:\PRODUCT-DOCS\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[13].oneOf[1].use[3]!C:\PRODUCT-DOCS\node_modules\mini-css-extract-plugin\dist\loader.js??ruleSet[1].rules[16].oneOf[1].use[0]!C:\PRODUCT-DOCS\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[16].oneOf[1].use[1]!C:\PRODUCT-DOCS\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[16].oneOf[1].use[2]!C:\PRODUCT-DOCS\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[16].oneOf[1].use[3]!C:\PRODUCT-DOCS\src\css\custom\main.scss
client (webpack 5.75.0) compiled with 4 errors

```

## Your Environment

- Version used: 2.0.0-beta.2
- Operating System and version (desktop or mobile): Desktop, Windows 10

**Comment by blindaa121** [comment]
Hi @Zenahr! We've just released `v2.0.0-beta-3` which includes a fix for this error. Let us know how it works 👍

**Comment by Mikescops** [comment]
Hey @blindaa121, the error still happens even with `beta.4`.

**Comment by Mikescops** [comment]
Sounds like a separated issue. Let me open a new one.
